version: '3.1'
services:
  db:
    container_name: postgres_db
    image: postgres:13-alpine
    restart: always
    hostname: postgres_db
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: pgtest
      POSTGRES_PASSWORD: pgtest
      POSTGRES_DB: neutral

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - /var/lib/pgadmin
    restart: always
    ports:
      - 8081:8081
    environment:
      PGADMIN_DEFAULT_EMAIL: pgtest@email.com
      PGADMIN_DEFAULT_PASSWORD: pgtest
      PGADMIN_LISTEN_PORT: 8081
